// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: synsData2Algolia/algolia_sync.proto

package algoliaSync

import (
	fmt "fmt"
	common "github.com/cargod-bj/b2c-proto-common/common"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/micro/go-micro/v2/api"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for AlgoliaSync service

func NewAlgoliaSyncEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for AlgoliaSync service

type AlgoliaSyncService interface {
	//  推送carlist
	SyncCarList(ctx context.Context, in *common.EmptyDto, opts ...client.CallOption) (*common.Response, error)
	//  推送失败重试
	RetrySyncCar(ctx context.Context, in *common.EmptyDto, opts ...client.CallOption) (*common.Response, error)
}

type algoliaSyncService struct {
	c    client.Client
	name string
}

func NewAlgoliaSyncService(name string, c client.Client) AlgoliaSyncService {
	return &algoliaSyncService{
		c:    c,
		name: name,
	}
}

func (c *algoliaSyncService) SyncCarList(ctx context.Context, in *common.EmptyDto, opts ...client.CallOption) (*common.Response, error) {
	req := c.c.NewRequest(c.name, "AlgoliaSync.SyncCarList", in)
	out := new(common.Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *algoliaSyncService) RetrySyncCar(ctx context.Context, in *common.EmptyDto, opts ...client.CallOption) (*common.Response, error) {
	req := c.c.NewRequest(c.name, "AlgoliaSync.RetrySyncCar", in)
	out := new(common.Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for AlgoliaSync service

type AlgoliaSyncHandler interface {
	//  推送carlist
	SyncCarList(context.Context, *common.EmptyDto, *common.Response) error
	//  推送失败重试
	RetrySyncCar(context.Context, *common.EmptyDto, *common.Response) error
}

func RegisterAlgoliaSyncHandler(s server.Server, hdlr AlgoliaSyncHandler, opts ...server.HandlerOption) error {
	type algoliaSync interface {
		SyncCarList(ctx context.Context, in *common.EmptyDto, out *common.Response) error
		RetrySyncCar(ctx context.Context, in *common.EmptyDto, out *common.Response) error
	}
	type AlgoliaSync struct {
		algoliaSync
	}
	h := &algoliaSyncHandler{hdlr}
	return s.Handle(s.NewHandler(&AlgoliaSync{h}, opts...))
}

type algoliaSyncHandler struct {
	AlgoliaSyncHandler
}

func (h *algoliaSyncHandler) SyncCarList(ctx context.Context, in *common.EmptyDto, out *common.Response) error {
	return h.AlgoliaSyncHandler.SyncCarList(ctx, in, out)
}

func (h *algoliaSyncHandler) RetrySyncCar(ctx context.Context, in *common.EmptyDto, out *common.Response) error {
	return h.AlgoliaSyncHandler.RetrySyncCar(ctx, in, out)
}
