// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: campaignNotice/campaign_notice.proto

package campaignNotice

import (
	fmt "fmt"
	common "github.com/cargod-bj/b2c-proto-common/common"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/micro/go-micro/v2/api"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for CampaignNotice service

func NewCampaignNoticeEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for CampaignNotice service

type CampaignNoticeService interface {
	Notice(ctx context.Context, in *common.EmptyDto, opts ...client.CallOption) (*common.Response, error)
}

type campaignNoticeService struct {
	c    client.Client
	name string
}

func NewCampaignNoticeService(name string, c client.Client) CampaignNoticeService {
	return &campaignNoticeService{
		c:    c,
		name: name,
	}
}

func (c *campaignNoticeService) Notice(ctx context.Context, in *common.EmptyDto, opts ...client.CallOption) (*common.Response, error) {
	req := c.c.NewRequest(c.name, "CampaignNotice.Notice", in)
	out := new(common.Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for CampaignNotice service

type CampaignNoticeHandler interface {
	Notice(context.Context, *common.EmptyDto, *common.Response) error
}

func RegisterCampaignNoticeHandler(s server.Server, hdlr CampaignNoticeHandler, opts ...server.HandlerOption) error {
	type campaignNotice interface {
		Notice(ctx context.Context, in *common.EmptyDto, out *common.Response) error
	}
	type CampaignNotice struct {
		campaignNotice
	}
	h := &campaignNoticeHandler{hdlr}
	return s.Handle(s.NewHandler(&CampaignNotice{h}, opts...))
}

type campaignNoticeHandler struct {
	CampaignNoticeHandler
}

func (h *campaignNoticeHandler) Notice(ctx context.Context, in *common.EmptyDto, out *common.Response) error {
	return h.CampaignNoticeHandler.Notice(ctx, in, out)
}
