// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.22.0
// 	protoc        v3.15.8
// source: cmsPic/cms_pic.proto

package cmsPic

import (
	common "github.com/cargod-bj/b2c-proto-common/common"
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type CmsCondDTO struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ids []uint64 `protobuf:"varint,1,rep,packed,name=ids,proto3" json:"ids,omitempty"`
}

func (x *CmsCondDTO) Reset() {
	*x = CmsCondDTO{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmsPic_cms_pic_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CmsCondDTO) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CmsCondDTO) ProtoMessage() {}

func (x *CmsCondDTO) ProtoReflect() protoreflect.Message {
	mi := &file_cmsPic_cms_pic_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CmsCondDTO.ProtoReflect.Descriptor instead.
func (*CmsCondDTO) Descriptor() ([]byte, []int) {
	return file_cmsPic_cms_pic_proto_rawDescGZIP(), []int{0}
}

func (x *CmsCondDTO) GetIds() []uint64 {
	if x != nil {
		return x.Ids
	}
	return nil
}

type CmsPicDTOList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CmsPicDTO []*CmsPicDTO `protobuf:"bytes,1,rep,name=cmsPicDTO,proto3" json:"cmsPicDTO,omitempty"`
}

func (x *CmsPicDTOList) Reset() {
	*x = CmsPicDTOList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmsPic_cms_pic_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CmsPicDTOList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CmsPicDTOList) ProtoMessage() {}

func (x *CmsPicDTOList) ProtoReflect() protoreflect.Message {
	mi := &file_cmsPic_cms_pic_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CmsPicDTOList.ProtoReflect.Descriptor instead.
func (*CmsPicDTOList) Descriptor() ([]byte, []int) {
	return file_cmsPic_cms_pic_proto_rawDescGZIP(), []int{1}
}

func (x *CmsPicDTOList) GetCmsPicDTO() []*CmsPicDTO {
	if x != nil {
		return x.CmsPicDTO
	}
	return nil
}

type CmsPicDTO struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          uint64   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	NickName    string   `protobuf:"bytes,2,opt,name=nickName,proto3" json:"nickName,omitempty"`
	UserName    string   `protobuf:"bytes,3,opt,name=userName,proto3" json:"userName,omitempty"`
	StoreIds    []uint64 `protobuf:"varint,4,rep,packed,name=storeIds,proto3" json:"storeIds,omitempty"`
	AuthorityId string   `protobuf:"bytes,5,opt,name=authorityId,proto3" json:"authorityId,omitempty"`
	Email       string   `protobuf:"bytes,6,opt,name=email,proto3" json:"email,omitempty"`
}

func (x *CmsPicDTO) Reset() {
	*x = CmsPicDTO{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmsPic_cms_pic_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CmsPicDTO) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CmsPicDTO) ProtoMessage() {}

func (x *CmsPicDTO) ProtoReflect() protoreflect.Message {
	mi := &file_cmsPic_cms_pic_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CmsPicDTO.ProtoReflect.Descriptor instead.
func (*CmsPicDTO) Descriptor() ([]byte, []int) {
	return file_cmsPic_cms_pic_proto_rawDescGZIP(), []int{2}
}

func (x *CmsPicDTO) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CmsPicDTO) GetNickName() string {
	if x != nil {
		return x.NickName
	}
	return ""
}

func (x *CmsPicDTO) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *CmsPicDTO) GetStoreIds() []uint64 {
	if x != nil {
		return x.StoreIds
	}
	return nil
}

func (x *CmsPicDTO) GetAuthorityId() string {
	if x != nil {
		return x.AuthorityId
	}
	return ""
}

func (x *CmsPicDTO) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type StoreRoleReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StoreId   uint64 `protobuf:"varint,1,opt,name=storeId,proto3" json:"storeId,omitempty"`
	StoreRole string `protobuf:"bytes,2,opt,name=storeRole,proto3" json:"storeRole,omitempty"`
}

func (x *StoreRoleReq) Reset() {
	*x = StoreRoleReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmsPic_cms_pic_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StoreRoleReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreRoleReq) ProtoMessage() {}

func (x *StoreRoleReq) ProtoReflect() protoreflect.Message {
	mi := &file_cmsPic_cms_pic_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreRoleReq.ProtoReflect.Descriptor instead.
func (*StoreRoleReq) Descriptor() ([]byte, []int) {
	return file_cmsPic_cms_pic_proto_rawDescGZIP(), []int{3}
}

func (x *StoreRoleReq) GetStoreId() uint64 {
	if x != nil {
		return x.StoreId
	}
	return 0
}

func (x *StoreRoleReq) GetStoreRole() string {
	if x != nil {
		return x.StoreRole
	}
	return ""
}

var File_cmsPic_cms_pic_proto protoreflect.FileDescriptor

var file_cmsPic_cms_pic_proto_rawDesc = []byte{
	0x0a, 0x14, 0x63, 0x6d, 0x73, 0x50, 0x69, 0x63, 0x2f, 0x63, 0x6d, 0x73, 0x5f, 0x70, 0x69, 0x63,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x63, 0x6d, 0x73, 0x50, 0x69, 0x63, 0x1a, 0x39,
	0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x63, 0x61, 0x72, 0x67, 0x6f,
	0x64, 0x2d, 0x62, 0x6a, 0x2f, 0x62, 0x32, 0x63, 0x2d, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2d, 0x63,
	0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x63, 0x6f, 0x6d,
	0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x1e, 0x0a, 0x0a, 0x43, 0x6d, 0x73,
	0x43, 0x6f, 0x6e, 0x64, 0x44, 0x54, 0x4f, 0x12, 0x10, 0x0a, 0x03, 0x69, 0x64, 0x73, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x04, 0x52, 0x03, 0x69, 0x64, 0x73, 0x22, 0x40, 0x0a, 0x0d, 0x43, 0x6d, 0x73,
	0x50, 0x69, 0x63, 0x44, 0x54, 0x4f, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x2f, 0x0a, 0x09, 0x63, 0x6d,
	0x73, 0x50, 0x69, 0x63, 0x44, 0x54, 0x4f, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x11, 0x2e,
	0x63, 0x6d, 0x73, 0x50, 0x69, 0x63, 0x2e, 0x43, 0x6d, 0x73, 0x50, 0x69, 0x63, 0x44, 0x54, 0x4f,
	0x52, 0x09, 0x63, 0x6d, 0x73, 0x50, 0x69, 0x63, 0x44, 0x54, 0x4f, 0x22, 0xa7, 0x01, 0x0a, 0x09,
	0x43, 0x6d, 0x73, 0x50, 0x69, 0x63, 0x44, 0x54, 0x4f, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x6e, 0x69, 0x63,
	0x6b, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6e, 0x69, 0x63,
	0x6b, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x4e, 0x61, 0x6d,
	0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x4e, 0x61, 0x6d,
	0x65, 0x12, 0x1a, 0x0a, 0x08, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x49, 0x64, 0x73, 0x18, 0x04, 0x20,
	0x03, 0x28, 0x04, 0x52, 0x08, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x49, 0x64, 0x73, 0x12, 0x20, 0x0a,
	0x0b, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x69, 0x74, 0x79, 0x49, 0x64, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0b, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x69, 0x74, 0x79, 0x49, 0x64, 0x12,
	0x14, 0x0a, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x65, 0x6d, 0x61, 0x69, 0x6c, 0x22, 0x46, 0x0a, 0x0c, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x52, 0x6f,
	0x6c, 0x65, 0x52, 0x65, 0x71, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x49, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x07, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x49, 0x64, 0x12,
	0x1c, 0x0a, 0x09, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x52, 0x6f, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x09, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x52, 0x6f, 0x6c, 0x65, 0x32, 0x82, 0x01,
	0x0a, 0x06, 0x43, 0x6d, 0x73, 0x50, 0x69, 0x63, 0x12, 0x34, 0x0a, 0x0a, 0x47, 0x65, 0x74, 0x50,
	0x69, 0x63, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x12, 0x2e, 0x63, 0x6d, 0x73, 0x50, 0x69, 0x63, 0x2e,
	0x43, 0x6d, 0x73, 0x43, 0x6f, 0x6e, 0x64, 0x44, 0x54, 0x4f, 0x1a, 0x10, 0x2e, 0x63, 0x6f, 0x6d,
	0x6d, 0x6f, 0x6e, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x42,
	0x0a, 0x16, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x73, 0x42, 0x79, 0x53, 0x74, 0x6f, 0x72,
	0x65, 0x41, 0x6e, 0x64, 0x52, 0x6f, 0x6c, 0x65, 0x12, 0x14, 0x2e, 0x63, 0x6d, 0x73, 0x50, 0x69,
	0x63, 0x2e, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x52, 0x6f, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x10,
	0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x00, 0x42, 0x2d, 0x5a, 0x2b, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d,
	0x2f, 0x63, 0x61, 0x72, 0x67, 0x6f, 0x64, 0x2d, 0x62, 0x6a, 0x2f, 0x62, 0x32, 0x63, 0x2d, 0x67,
	0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x2d, 0x61, 0x70, 0x69, 0x2f, 0x63, 0x6d, 0x73, 0x50, 0x69,
	0x63, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_cmsPic_cms_pic_proto_rawDescOnce sync.Once
	file_cmsPic_cms_pic_proto_rawDescData = file_cmsPic_cms_pic_proto_rawDesc
)

func file_cmsPic_cms_pic_proto_rawDescGZIP() []byte {
	file_cmsPic_cms_pic_proto_rawDescOnce.Do(func() {
		file_cmsPic_cms_pic_proto_rawDescData = protoimpl.X.CompressGZIP(file_cmsPic_cms_pic_proto_rawDescData)
	})
	return file_cmsPic_cms_pic_proto_rawDescData
}

var file_cmsPic_cms_pic_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_cmsPic_cms_pic_proto_goTypes = []interface{}{
	(*CmsCondDTO)(nil),      // 0: cmsPic.CmsCondDTO
	(*CmsPicDTOList)(nil),   // 1: cmsPic.CmsPicDTOList
	(*CmsPicDTO)(nil),       // 2: cmsPic.CmsPicDTO
	(*StoreRoleReq)(nil),    // 3: cmsPic.StoreRoleReq
	(*common.Response)(nil), // 4: common.Response
}
var file_cmsPic_cms_pic_proto_depIdxs = []int32{
	2, // 0: cmsPic.CmsPicDTOList.cmsPicDTO:type_name -> cmsPic.CmsPicDTO
	0, // 1: cmsPic.CmsPic.GetPicInfo:input_type -> cmsPic.CmsCondDTO
	3, // 2: cmsPic.CmsPic.GetUsersByStoreAndRole:input_type -> cmsPic.StoreRoleReq
	4, // 3: cmsPic.CmsPic.GetPicInfo:output_type -> common.Response
	4, // 4: cmsPic.CmsPic.GetUsersByStoreAndRole:output_type -> common.Response
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_cmsPic_cms_pic_proto_init() }
func file_cmsPic_cms_pic_proto_init() {
	if File_cmsPic_cms_pic_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_cmsPic_cms_pic_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CmsCondDTO); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmsPic_cms_pic_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CmsPicDTOList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmsPic_cms_pic_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CmsPicDTO); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmsPic_cms_pic_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StoreRoleReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_cmsPic_cms_pic_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_cmsPic_cms_pic_proto_goTypes,
		DependencyIndexes: file_cmsPic_cms_pic_proto_depIdxs,
		MessageInfos:      file_cmsPic_cms_pic_proto_msgTypes,
	}.Build()
	File_cmsPic_cms_pic_proto = out.File
	file_cmsPic_cms_pic_proto_rawDesc = nil
	file_cmsPic_cms_pic_proto_goTypes = nil
	file_cmsPic_cms_pic_proto_depIdxs = nil
}
