// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: cmsPic/cms_pic.proto

package cmsPic

import (
	fmt "fmt"
	common "github.com/cargod-bj/b2c-proto-common/common"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/micro/go-micro/v2/api"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for CmsPic service

func NewCmsPicEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for CmsPic service

type CmsPicService interface {
	GetPicInfo(ctx context.Context, in *CmsCondDTO, opts ...client.CallOption) (*common.Response, error)
}

type cmsPicService struct {
	c    client.Client
	name string
}

func NewCmsPicService(name string, c client.Client) CmsPicService {
	return &cmsPicService{
		c:    c,
		name: name,
	}
}

func (c *cmsPicService) GetPicInfo(ctx context.Context, in *CmsCondDTO, opts ...client.CallOption) (*common.Response, error) {
	req := c.c.NewRequest(c.name, "CmsPic.GetPicInfo", in)
	out := new(common.Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for CmsPic service

type CmsPicHandler interface {
	GetPicInfo(context.Context, *CmsCondDTO, *common.Response) error
}

func RegisterCmsPicHandler(s server.Server, hdlr CmsPicHandler, opts ...server.HandlerOption) error {
	type cmsPic interface {
		GetPicInfo(ctx context.Context, in *CmsCondDTO, out *common.Response) error
	}
	type CmsPic struct {
		cmsPic
	}
	h := &cmsPicHandler{hdlr}
	return s.Handle(s.NewHandler(&CmsPic{h}, opts...))
}

type cmsPicHandler struct {
	CmsPicHandler
}

func (h *cmsPicHandler) GetPicInfo(ctx context.Context, in *CmsCondDTO, out *common.Response) error {
	return h.CmsPicHandler.GetPicInfo(ctx, in, out)
}
